package org.agrfesta.sh.api.domain.failures

sealed interface TemperatureSettingCreationFailure

data object OverlappingIntervals : TemperatureSettingCreationFailure

sealed interface TemperatureSettingDeletionFailure

sealed interface TemperatureSettingRetrievalFailure
