name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          # Exclude all dependencies that originate solely in the 'buildSrc' project
          dependency-graph-exclude-projets: ':buildSrc'
          # Exclude dependencies that are only resolved in test classpaths
          dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
